# permissions for end users to view jobdeletors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobdeletor-viewer-role
rules:
- apiGroups:
  - mikutas.example.com
  resources:
  - jobdeletors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mikutas.example.com
  resources:
  - jobdeletors/status
  verbs:
  - get
