
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - mikutas.example.com
  resources:
  - jobdeletors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mikutas.example.com
  resources:
  - jobdeletors/finalizers
  verbs:
  - update
- apiGroups:
  - mikutas.example.com
  resources:
  - jobdeletors/status
  verbs:
  - get
  - patch
  - update
