apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-10
spec:
  template:
    spec:
      containers:
      - name: sleeper
        image: alpine
        command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 4 # 6 by default
